### PR TITLE
Paq 2.0

### LINKED ISSUE #73: Switch whether plugins optional without reinstalling them?
The current behavior is that if `:PaqClean` is invoked with some plugins listed with `opt=true`, and they exist in the `start` dir, they are just deleted. I think it would be better if paq just moved the plugins to the `opt` dir in that case and also the converse. That would also help on testing some plugins like mentioned in #20, without having to navigate to the `pack` dir and moving them manually.

### LINKED ISSUE #80: `PaqSync` doesn't re-install plugins when `branch` is changed
### Bug

Change the `branch` of one plugin, run `:PaqSync` and the plugin stays the same

### Workaround

Comment the plugin (with the `branch` property), run `:PaqSync` in order to uninstall it, then uncomment and run `:PaqSync` again in order for the plugin to be installed from the correct branch

### LINKED ISSUE #99: Paq doesn't reinstall a plugin when remote is changed
**Describe the bug**
When switching a plugin from one git remote to another git remote, Paq doesn't recognize that and doesn't upgrade the plugin.

**To Reproduce**
1. Install a package: e.g. `'glepnir/lspsaga.nvim';` && `PaqInstall`
2. Change the package source: e.g. `'tami5/lspsaga.nvim';`
3. Run `PaqSync`

**Expected behavior**
It is expected that Paq will recognize that the package source change, and re-install it. Either by manually changing the git-remote and doing git-pull, or (to be on the safe side) by deleting the original package and installing the new one.

**Environment:**
 - `nvim --version`:
    ```NVIM v0.6.0
    Build type: RelWithDebInfo
    LuaJIT 2.1.0-beta3
    Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
    Compiled by runner@fv-az65-618

    Features: +acl +iconv +tui
    See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
   fall-back for $VIM: "/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

    Run :checkhealth for more info
    ```
- `git --version`: `git version 2.25.1`
- OS: 
    ```cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=20.04
    DISTRIB_CODENAME=focal
    DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
    ```

### LINKED ISSUE #107: Add a lockfile mechanism
A lot of issues with Paq right now stem from the fact that it doesn't have any kind of persistent state. All information is either in the user's configuration or in the git repo itself. However,

* Expecting the user to add more information in their config defeats the purpose of Paq. They could just use git submodules...
* Querying `git` using stdio is tedious and error-prone.
  - Lua has very limited string/stream manipulation facilities
  - Using libgit2 bindings seems to be out of the question :(

The easiest way to solve this seems to be storing information in a file so that Paq has an easier time telling what has changed since it was last called.

The lockfile could be used for "reproducible" neovim configs.

### LINKED ISSUE #150: Error when using extra parameters with plugins.
**Describe the bug**
I was cleaning up and adding some plugins around the time of the latest commit. I have paq configured to manage itself, so a `:PaqSync` probably updated it. I get this when running PaqSync now:

```
E5108: Error executing lua ...cal/share/nvim/site/pack/paqs/start/paq-nvim/lua/paq.lua:98: Cannot serialise function: type not supported
stack traceback:
        [C]: in function 'error'
        ...cal/share/nvim/site/pack/paqs/start/paq-nvim/lua/paq.lua:98: in function 'state_write'
        ...cal/share/nvim/site/pack/paqs/start/paq-nvim/lua/paq.lua:297: in function 'exe_op'
        ...cal/share/nvim/site/pack/paqs/start/paq-nvim/lua/paq.lua:353: in function 'clean'
        ...cal/share/nvim/site/pack/paqs/start/paq-nvim/lua/paq.lua:354: in function 'sync'
        [string ":lua"]:1: in main chunk
```

I removed the last plugin I added before the error, thinking it might be the cause, but the error remained. After some commenting, I've narrowed it down to this line in my config:

```lua
require "paq" {
    ...
    { "nvim-treesitter/nvim-treesitter", run = function () vim.cmd[[TSUpdate]] end },
    ...
```

There's no errors if I simply have `"nvim-treesitter/nvim-treesitter",` instead.

**To Reproduce**
Use the following with `nvim -u`:
```lua
require "paq" {
    "savq/paq-nvim",
    { "kvrohit/rasmus.nvim", run = function () print("hello") end },
}
```

**Expected behavior**
No errors.

**Environment:**
- Arch Linux
- `nvim --version`:
```
NVIM v0.9.0-dev-18-ga93ff5fc6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az96-559

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info```
```

### PR DESCRIPTION
**Pull request by saccarosium**
### BREAKING CHANGES:

- The `run` option is deprecated. Use `build` instead.
- Similarly, the `PaqRunHook` is deprecated in favor of `PaqBuild`.
- The `paq`/`register` function was removed.

----

I think we are ready to ship paq 2.0. We need to made some small modifications but I think we are there.

I have some questions regarding the documentation. If we are gonna annotate the source with emmylua comment, what documentation generator we'll going to use? [mini.doc](https://github.com/echasnovski/mini.doc) or [lemmy-help](https://github.com/numToStr/lemmy-help)?

When I've tried do documentation with emmylua comments, I found myself unwrapping a lot of the code since parsers didn't play nicely with things such as metatables. Also is worth noting that most of the documentation, found in the `paq-nvim.txt`, doesn't really belong anywhere in the codebase. Leading to having pretty big wall of comments at the begin and end of the file and nothing in the middle.

----

- Closes #107
- Closes #73
- Closes #80
- Closes #99 
- Closes #150

### CODE REVIEW

**Comment by savq** [comment]
> Also is worth noting that most of the documentation, found in the paq-nvim.txt, doesn't really belong anywhere in the codebase.

Yeah, fortunately the public API is rather small. I'd really like for Paq to be one file, but not even vim-plug embeds the docs. I don't think this is blocking, and I'll move the doc ideas out of the tracking issue.

**Comment by saccarosium** [comment]
Pretty happy with the result. I think we are ready to ship it.

File: lua/paq.lua [hunk 1]
```diff
@@ -226,95 +187,365 @@ local function log_update_changes(pkg, prev_hash, cur_hash)
...
+    local file = uv.fs_open(Config.lock, "w", 438)
+    if file then
+        local ok, result = pcall(vim.json.encode, pkgs)
+        if not ok then
+            error(result)
+        end
+        assert(uv.fs_write(file, result))
+        assert(uv.fs_close(file))
+    end
+    Lock = Packages
```
Comment (savq) [inline lua/paq.lua:241]: Should this be a `deepcopy`? In case the user calls `paq.__call` again.

**Review by savq — CHANGES_REQUESTED** [review]
I finished checking all the changes.

I think there's only a tiny change needed, otherwise we're good to go!

File: lua/paq.lua (hunk 1 above)
Comment (saccarosium) [reply lua/paq.lua:241]: Previously I was using `deepcopy` but it doesn't really make a difference. I opted to this solution since is cheaper to pass the table by reference instead of coping deeply the entire content. But we could use either and it will work the same.

**Review by savq — APPROVED** [review]

**Comment by savq** [comment]
Thank you @saccarosium for all the work you've done.

I don't think there's any more breaking changes or big changes to make, so we can continue working on smaller stuff in separate PRs.
